### ISSUE TITLE
How to Delete a User Account

### ISSUE THREAD

**Issue by vizem** [evoWeb/sf_register#12]
Hi,
how to delete  a user account ?

Thanks,
Best regards,
vizem

**Comment by garbast** [comment]
Thats not scope of a registration. It wont.

**Comment by AstCommodore** [comment]
Moin,
thanks a lot for your powerful extension!!!

Editing a user / changing its password is also not a scope of a registration only extension, but sf_register does both. ;)

Since 2016 it had changed a lot, maybe deleting an account is useful in times of the GDPR / DSGVO, isn't it? The same mechanism to enable a user (switch from temporary group to final) could implemented here to (switch from final group to deleted).

I didn't dig deep into the code, but maybe it's not such a hard challenge?!

What's your meaning?
André

**Comment by garbast** [comment]
Feel free to hand in a pull request and i will have a look on it.
