### ISSUE TITLE
Case sensitive partials

### ISSUE THREAD

**Issue by Zillion01** [evoWeb/sf_register#142]
The partials CaptchaSrFreecap.html and Textfield.html should be renamed to CaptchaSrfreecap.html and TextField.html. On Linux case sensitive sytems these partials cannot be found.

**Comment by garbast** [comment]
For Textfield.html i strongly disagree because in Typoscript the fields that uses this partial are configured as followed
```
username.partial = Textfield
```
The property .partial defines what file to use and as such the uppercase F would break it.

In case of srfreecap, you are right, the <f:render partial="Captcha{options.type -> f:format.case(mode: 'capital')}" /> viewhelper just uppercase the first letter of the type, which i assume is srfreecap as it is configured in Common/setup.typoscript.

**Comment by Zillion01** [comment]
TextField probably caused by Partials/CaptchaSrFreecap.html `partial="Form/TextField"`
