### ISSUE TITLE
Validation of all fields is not working in v11 because controller error causes disfunctionality

### ISSUE THREAD

**Issue by zloy88** [evoWeb/sf_register#171]
Using TYPO3 11 with PHP 8.1 and followed whole basic instructions. It is possible to submit empty form, all validators are not working.

Steps to reproduce:

* Use T3 v11
* Use PHP 8.1
* Include minimal TypoScript on page root
* set necessary constants like user_group etc. 
* place sfregister_create plugin on any page and add storagePid
* open page in frontend and submit form empty
* result: Call to a member function getUid() on array -> typo3conf/ext/sf_register/Classes/Controller/FeuserCreateController.php line 48 

EDIT:
I don't understand the sense of line 42 - 51 - when i uncomment those lines the validation is working correctly.
After validation is working again, i noticed another error in the error messages in the frontend. If i try to register a new user  where the username is not unique, the error that the username is not unique is thrown twice.

**Comment by garbast** [comment]
To reproduce the problem, I installed 
TYPO3 11.5.4
sf_register dev-develop
on Apache 2.4.41 (Ubuntu) with PHP 8.1.0. 

After that I 
create a storage folder for the data
a page for the plugin
added the plugin with default fields
selected the storage folder in the plugin as record storage
added the minimal typoscript in my typoscript record
opend the registration page
left the form empty and submitted the form

All i got was the previous form and lots of errors of missing fields. Lines 42 to 51 are not relevant to the problem you describe. You were saying, that the validation does not work. If so, the form would be submitted and you would see the preview output.

Also the error described that line would cause an error is not possible any more, because the condition checks if there is a user model and then access the getUid method.

But IF you see the error in line 48 it clearly indicates that the validation worked perfectly or else you would never have an $originalRequest containing an user entry.
