### ISSUE TITLE
InvalidEnumerationValueException when register with usergroup

### ISSUE THREAD

**Issue by soerenwachsmuth** [evoWeb/sf_register#180]
Hello,

im using TYPO3 10.4.21, with the latest sf_register 10.1.5.

When i configure the extension to not using usergroups after create the user, everything works fine.
But when i activate it it throws the following error:

(1/1) #1381512761 TYPO3\CMS\Core\Type\Exception\InvalidEnumerationValueException
Invalid value "LANGUAGE" for enumeration "TYPO3\CMS\Core\DataHandling\TableColumnType"

Would be gratefull for any help.

Thank you in advance and best regards,
Sören

**Comment by garbast** [comment]
Please upgrade to 10.2.0 and check if this behaviour still happens.

**Comment by soerenwachsmuth** [comment]
Thank you very much for your answer.

But that doesn't fix that issue.

**Comment by garbast** [comment]
Sorry to read that. In my installation, consisting of only TYPO3 10.4.23 and sf_register 10.2.0 (it shows 10.1.7 in extension manager because of missing update of ext_emconf.php), i cant reproduce the error.

My TypoScript setup is:
plugin.tx_sfregister.settings {
  useEmailAddressAsUsername = 1
  
  usergroupPostSave = 1
  usergroupPostConfirm = 2
  
  notifyUser.createSave = 1
}
