### ISSUE TITLE
Date of Birth as not required, but saved to database with defaults

### ISSUE THREAD

**Issue by heural** [evoWeb/sf_register#233]
The problem is, that the date-of-birth fields has default values and if these fields are not required, the date will still be stored in the database (1960-01-01). 
I think the default value has to be '-' and if the 3 fields are '-', then the date is´nt stored to database.

**Comment by garbast** [comment]
The DateTimeConverter only changes the birthdate if 

            is_array($userData)
            && !empty($userData)
            && !empty($userData['dateOfBirthDay'] ?? '')
            && !empty($userData['dateOfBirthMonth'] ?? '')
            && !empty($userData['dateOfBirthYear'] ?? '')

The field FrontendUser::dateOfBirth is of DateTime. So if for what ever reason the field is not changed a 0 i stored in the database. And 0 in Date ist 1970-0-0. This is not caused by the sf_register but by the date format. The field date_of_birth is of type int(11) DEFAULT '0' NOT NULL which results in 0 in the field.

There is nothing wrong with which the field works. It is not a sql date field.

**Comment by garbast** [comment]
Take a look at the documentation and the typoscript provided by the extension. Its possible to remove validation for fields.

This is not a support forum for your installation. Individual support is only available on a paid base.

**Comment by heural** [comment]
I'am not sure if you understand me ;-)
The validation is not the cause/problem. Its not my installation, it´s your code in the comment before [https://github.com/evoWeb/sf_register/blob/11.x/Resources/Private/Partials/Form/DateSelect.html](https://github.com/evoWeb/sf_register/blob/11.x/Resources/Private/Partials/Form/DateSelect.html)

![screenshot-aimeos local-2023 08 31-08_12_11](https://github.com/evoWeb/sf_register/assets/25622396/659cb94b-67ec-4d3a-824d-45273b5975de)
