### ISSUE TITLE
Autologin doesn't work

### ISSUE THREAD

**Issue by simonschaufi** [evoWeb/sf_register#257]
The extension creates a URL in \Evoweb\SfRegister\Controller\FeuserController::autoLogin with a nonce request token and then redirects to that URL. After the redirect TYPO3 should verify that the token is valid through a cookie that was set before but reading the value from cookie is only done in POST/PUT/PATCH requests but not GET requests. That causes an issue in the BeforeRequestTokenProcessedListener where the request token is read from the URL but can't be verified because the internal NoncePool has an empty items array.

The problem lies most likely in the RequestTokenMiddleware where the nonce is read from the request and then added to the nonce pool. The request token is either read from the request header or from the POST body but since the request is done with a GET request, it is empty at this point.

I hope this issue can be solved somehow without patching the core.

**Comment by garbast** [comment]
Could you please add your TYPO3 version?

**Comment by simonschaufi** [comment]
V12 with latest release of the extension

**Comment by simonschaufi** [comment]
This is the solution:

Don't pass the request token in the URL but generate it in the event:

```php
use TYPO3\CMS\Core\Authentication\Event\BeforeRequestTokenProcessedEvent;
use TYPO3\CMS\Core\Security\RequestToken;
use TYPO3\CMS\Frontend\Authentication\FrontendUserAuthentication;

final readonly class BeforeRequestTokenProcessedListener
{
    public function __invoke(BeforeRequestTokenProcessedEvent $event): void
    {
        $requestToken = $event->getRequestToken();
        // fine, there is a valid request token
        if ($requestToken instanceof RequestToken) {
            return;
        }

        $user = $event->getUser();
        if (!$user instanceof FrontendUserAuthentication) {
            return;
        }
        $requestToken = RequestToken::create('core/user-auth/' . strtolower($user->loginType));
        $event->setRequestToken($requestToken);
    }
}
```

**Comment by garbast** [comment]
@simonschaufi did it work for you with the provided configuration?

plugin.tx_sfregister.settings.autologinPostRegistration = 1
plugin.tx_sfregister.settings.useEmailAddressAsUsername = 1
plugin.tx_sfregister.settings.redirectPostRegistrationPageId = 7

**Comment by simonschaufi** [comment]
This is exactly what I have as well in my constants but it doesn't work for me.

**Comment by garbast** [comment]
I had a better look into the proposed change to the BeforeRequestTokenProcessedListener. I'm not a big fan of it, because it disables the purpose of the request token check completely. With this event listener your system behaves as if there is no request token system at all.

I like the early return if a request is provided or if the event was triggered in backend authentication. These two conditions i integrate, but i will stick to the mechanism to get the logintype and the _RequestToken from the request.

From checking the autologin function in the feuser controller the only idea i can come up with is, that the login uses the php $_SESSION. Could it be, that your installation has some problem with that?

After this closer inspection, i still cant reproduce it in v12 and v13
