### ISSUE TITLE
[Semantical Error] Couldn't find constant Evoweb\SfRegister\Validation\Validator\RepeatValidator.

### ISSUE THREAD

**Issue by netzcoop** [evoWeb/sf_register#74]
hello  sf_register team

i have a problem since the commit d659d5fa720d2b213fafcbcfc3c524ed39be5cdb  with the Validation, before it works fine.

kind regards 

(1/1) Doctrine\Common\Annotations\AnnotationException
[Semantical Error] Couldn't find constant Evoweb\SfRegister\Validation\Validator\RepeatValidator.
in /var/www/itsc/TYPO3.CMS/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php line 54
`    public static function semanticalError($message)
    {
        return new self('[Semantical Error] ' . $message);
    }`

.....

at Doctrine\Common\Annotations\DocParser->parse('@TYPO3\\CMS\\Extbase\\Annotation\\Validate(Evoweb\\SfRegister\\Validation\\Validator\\RepeatValidator)')
in typo3conf/ext/sf_register/Classes/Controller/FeuserController.php line 232
`        $validateAnnotation = current($parser->parse(
            '@TYPO3\CMS\Extbase\Annotation\Validate(' . $configuration . ')'
        ));`

**Comment by garbast** [comment]
Please have a look in the Breaking Changes documentation. The notation for validators was changed.

**Comment by garbast** [comment]
Fixed in c673512c4d5a90ef0039e5039af516f02b813870
Old validator config is handled as long as no options are used with the validator.

So ok:
- Evoweb\SfRegister\Validation\Validator\RepeatValidator
- EmailAdress

Not ok:
- StringLength(minimum = 4, maximum = 80)

The not ok validator configuration must be replaced.
The ok validators are adviced to be converted for better readability, like from Evoweb\SfRegister\Validation\Validator\RepeatValidator to "Evoweb.SfRegister:Required"

**Comment by netzcoop** [comment]
thanks for the answers and code
