### ISSUE TITLE
Edit-Form: Prefilled Data of logged in Users missing (useDataOfLoggedinFeuser )

### ISSUE THREAD

**Issue by UweJakobs** [evoWeb/sf_register#75]
Within the constants, you can set the Option "defines in edit mode if the fields get filled with data of logged in user" by plugin.tx_sfregister.settings.useDataOfLoggedinFeuser = 1.
However, this Feature seems to be missing in the Code.

**Comment by garbast** [comment]
After checking FeuserEditController:formAction i can confirm that useDataOfLoggedinFeuser is not used in there, but that is only because now it's default behaviour to always prefill the user object with already stored values.

So i will drop all other appearance of the config parameter useDataOfLoggedinFeuser.
