### ISSUE TITLE
Edit/Update-Process: Error with encryptPassword

### ISSUE THREAD

**Issue by UweJakobs** [evoWeb/sf_register#77]
Whenever I want to update the Profile, this error occurs:
Return value of Evoweb\SfRegister\Controller\FeuserController::encryptPassword() must be of the type string, null returned
in [...]typo3conf/ext/sf_register/Classes/Controller/FeuserController.php line 436

The Password-Field is not included in the Form and i did choose the "Update"-Button.

**Comment by garbast** [comment]
Hm that's suspicious because the edit controller does not calls the encryptPassword method. Do you realy edit a profile?

In total the encryptPassword is only called in FeuserCreateController::saveAction and  FeuserPasswordController::saveAction

In case you dont have the user enter the password on creation i added an check if the password is set in the save action. But remember, you need to provide a method that is storing an encrypted password after  confirmation by the user.
