### ISSUE TITLE
Generate "name" from "first_name" and "last_name"

### ISSUE THREAD

**Issue by UweJakobs** [evoWeb/sf_register#80]
Is there a possibility to generate Field-Contents out of the value of other fields? Like "name" from a concat of "first_name" and "last_name"? Didn't find it so far.

**Comment by garbast** [comment]
No this is not part of the feuser model. If you need that, you have to integrate a SignalSlot and use 
```
$user->setName($user->getFristName() . ' ' . $user->getLastName())
```
Beside i would not advise to use it like that. The combined field is more or less a simplification if you want to use only one field to both values.

Why do you want to use name instead of first_name last_name?

**Comment by garbast** [comment]
For this kind of "special needs" the SignalSlots are provided in every action before save or update in the repository.
