### ISSUE TITLE
Confirmation of user not possible without mail

### ISSUE THREAD

**Issue by Teddytrombone** [evoWeb/sf_register#92]
I have the following scenario: the extension is configured with 'notifyUserPostCreateSave = 1`. So if a user fills out the registration form the user record is disabled and a confirmation mail is sent to the users mail address with a link to activate the user record. But if the user looses the mail (spam filter or deletes the mail), it's not possible to register anymore with this username/email.

Maybe I missed something, but I guess there has to be a function like "resend activation mail". So in a similar way as the "password forgot"-function of EXT:felogin, so that the user get's a form with an input field for the mail address. After submitting the confirmation mail is sent again.

**Comment by garbast** [comment]
You are welcome to develop a PR with this feature

**Comment by garbast** [comment]
The functionality itself is working as expected. Still i cant get the deployment running due to a problem with the functional tests running into an problem with the YamlLoader of symfony/dependency-injection. Until the core does not release a 10.x with resolution to this, the next release to the TER will not happen. Still i will release a tag for composer.
