### ISSUE TITLE
double opt-in not working (no mails sent)

### ISSUE THREAD

**Issue by jowe1** [evoWeb/sf_register#95]
Hello,
I have tried installing your extension into a Typo3 9 LTS project. Everything works fine but there are no mails being sent even though the configuration should be set for double opt-in. Sending mails works fine in Typo3 (both locally with mailhog and on the test server with normal SMTP). I have also seen that the function confirmAction in Classes/Controller/FeuserCreateController.php is unused (PhpStorm notification). I am almost certain that this should be the function to send the mails.
I also could not find any function that generates a hash and implements the URL for the user to click on. So is this not finished in 9.4.0 of your extension or am I missing some part of it?
Also the documentation isn't really clear on how to set up the page TS properly, what would be the minimal configuration for double-opt-in to work?
Any help would be appreciated! Thanks for your effort.

**Comment by garbast** [comment]
The generation of the hashes are in \Evoweb\SfRegister\ViewHelpers\Link\ActionViewHelper

About the not sending, it's most likely a missconfiguration. You need to check your TypoScript setup if everything is fine.

Concerning the confirmAction, PhpStorm will never be able to find an Extbase controller action be used because they are called dynamically in ActionController::callActionMethod. This is by concept. 

```
$actionResult = $this->{$this->actionMethodName}(...$preparedArguments);
```

Support for individual installation is possible on invoice level.

**Comment by jowe1** [comment]
@garbast thanks for replying so quickly. So there's no error in PHP but what would be the minimal configuration for double opt-in to work? In https://docs.typo3.org/typo3cms/extensions/sf_register/stable/Configuration/Emails/Index.html it states that **confirmEmailPostCreate** is responsible but once I set it to true it still does not send E-Mails. Maybe I have put the configuration at the wrong location? Does it need to be in page TS on the registration page or in setup on root template or elsewhere?

Thanks again!
